### ISSUE TITLE
A bit of documentation would be nice

### ISSUE THREAD

**Issue by lukilukeskywalker** [estevetarra/Web-App-Votacions-BEST#3]
Presupongo que estos son unos archivos vuestros:

`/etc/letsencrypt/live/bestbarcelona.org/privkey.pem`

y luego, estos parametros:
`password = CLIENT_SECRET`
Hay que generarlos, hay un archivo con estos parametros, o los introcucimos manualmente?
Saludos desde LBG Madrid

**Comment by InigoMoreno** [comment]
`/etc/letsencrypt/live/bestbarcelona.org/privkey.pem`
Esto es el path al certificado https de nuestro servidor no se como funcionara en el vuestro.

lo de `CLIENT_SECRET` esta relacionado con lo de googlecredentials si miras un poco mas arriba la definicion es:
```
var obj = JSON.parse(fs.readFileSync('googlecredentials.pswd', 'utf8'));
var CLIENT_ID = obj['id'];
var CLIENT_SECRET = obj['secret'];
```
El archivo `googlecredentials.pswd` son unas credenciales del LBG que necesitas para usar la api de google, tendras que generar una copia para tu lbg [en este link](https://console.cloud.google.com/apis/credentials) y ponerla en la carpeta code.

**Comment by davidbatetc** [comment]
Actualmente estamos trabajando en actualizar la web app. Como parte del proyecto tenemos pensado también documentarla mejor.
